-- BRZ_SIH_RD — SIHSUS RD — AIH Reduzida, 1 linha = 1 internacao
-- Gerado por scripts/gen_external_tables.py. Nao editar a mao.
-- Fonte: 24 arquivo(s), RDSP2406 a RDSP2605
-- Colunas: 114
--
-- ATENCAO: 1 coluna(s) nao existem em todas as
-- competencias: FONTE_ORC
-- Ficam NULL nos arquivos que nao as tem. E por isso que o column_list e
-- declarado explicitamente em vez de inferido com 'schema' VALUE 'first'.
--
-- Substitua <REGIAO>, <NAMESPACE> e <BUCKET> antes de rodar (veja sql/external_tables/uris.txt).

BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'BRZ_SIH_RD',
    credential_name => 'OCI$RESOURCE_PRINCIPAL',
    file_uri_list   => 'https://objectstorage.<REGIAO>.oraclecloud.com/n/<NAMESPACE>/b/<BUCKET>/o/processed/sihsus/*.parquet',
    format          => JSON_OBJECT('type' VALUE 'parquet'),
    column_list     => '
      UF_ZI      VARCHAR2(10 CHAR),
      ANO_CMPT   VARCHAR2(10 CHAR),
      MES_CMPT   VARCHAR2(10 CHAR),
      ESPEC      VARCHAR2(10 CHAR),
      CGC_HOSP   VARCHAR2(17 CHAR),
      N_AIH      VARCHAR2(16 CHAR),
      IDENT      VARCHAR2(10 CHAR),
      CEP        VARCHAR2(10 CHAR),
      MUNIC_RES  VARCHAR2(10 CHAR),
      NASC       VARCHAR2(10 CHAR),
      SEXO       VARCHAR2(10 CHAR),
      UTI_MES_IN NUMBER(19),
      UTI_MES_AN NUMBER(19),
      UTI_MES_AL NUMBER(19),
      UTI_MES_TO NUMBER(19),
      MARCA_UTI  VARCHAR2(10 CHAR),
      UTI_INT_IN NUMBER(19),
      UTI_INT_AN NUMBER(19),
      UTI_INT_AL NUMBER(19),
      UTI_INT_TO NUMBER(19),
      DIAR_ACOM  NUMBER(19),
      QT_DIARIAS NUMBER(19),
      PROC_SOLIC VARCHAR2(13 CHAR),
      PROC_REA   VARCHAR2(13 CHAR),
      VAL_SH     NUMBER,
      VAL_SP     NUMBER,
      VAL_SADT   NUMBER,
      VAL_RN     NUMBER,
      VAL_ACOMP  NUMBER,
      VAL_ORTP   NUMBER,
      VAL_SANGUE NUMBER,
      VAL_SADTSR NUMBER,
      VAL_TRANSP NUMBER,
      VAL_OBSANG NUMBER,
      VAL_PED1AC NUMBER,
      VAL_TOT    NUMBER,
      VAL_UTI    NUMBER,
      US_TOT     NUMBER,
      DT_INTER   VARCHAR2(10 CHAR),
      DT_SAIDA   VARCHAR2(10 CHAR),
      DIAG_PRINC VARCHAR2(10 CHAR),
      DIAG_SECUN VARCHAR2(10 CHAR),
      COBRANCA   VARCHAR2(10 CHAR),
      NATUREZA   VARCHAR2(10 CHAR),
      NAT_JUR    VARCHAR2(10 CHAR),
      GESTAO     VARCHAR2(10 CHAR),
      RUBRICA    NUMBER(19),
      IND_VDRL   VARCHAR2(10 CHAR),
      MUNIC_MOV  VARCHAR2(10 CHAR),
      COD_IDADE  VARCHAR2(10 CHAR),
      IDADE      NUMBER(19),
      DIAS_PERM  NUMBER(19),
      MORTE      NUMBER(19),
      NACIONAL   VARCHAR2(10 CHAR),
      NUM_PROC   VARCHAR2(10 CHAR),
      CAR_INT    VARCHAR2(10 CHAR),
      TOT_PT_SP  NUMBER(19),
      CPF_AUT    VARCHAR2(10 CHAR),
      HOMONIMO   VARCHAR2(10 CHAR),
      NUM_FILHOS NUMBER(19),
      INSTRU     VARCHAR2(10 CHAR),
      CID_NOTIF  VARCHAR2(10 CHAR),
      CONTRACEP1 VARCHAR2(10 CHAR),
      CONTRACEP2 VARCHAR2(10 CHAR),
      GESTRISCO  VARCHAR2(10 CHAR),
      INSC_PN    VARCHAR2(15 CHAR),
      SEQ_AIH5   VARCHAR2(10 CHAR),
      CBOR       VARCHAR2(10 CHAR),
      CNAER      VARCHAR2(10 CHAR),
      VINCPREV   VARCHAR2(10 CHAR),
      GESTOR_COD VARCHAR2(10 CHAR),
      GESTOR_TP  VARCHAR2(10 CHAR),
      GESTOR_CPF VARCHAR2(19 CHAR),
      GESTOR_DT  VARCHAR2(10 CHAR),
      CNES       VARCHAR2(10 CHAR),
      CNPJ_MANT  VARCHAR2(17 CHAR),
      INFEHOSP   VARCHAR2(10 CHAR),
      CID_ASSO   VARCHAR2(10 CHAR),
      CID_MORTE  VARCHAR2(10 CHAR),
      COMPLEX    VARCHAR2(10 CHAR),
      FINANC     VARCHAR2(10 CHAR),
      FAEC_TP    VARCHAR2(10 CHAR),
      REGCT      VARCHAR2(10 CHAR),
      RACA_COR   VARCHAR2(10 CHAR),
      ETNIA      VARCHAR2(10 CHAR),
      SEQUENCIA  NUMBER(19),
      REMESSA    VARCHAR2(26 CHAR),
      AUD_JUST   VARCHAR2(61 CHAR),
      SIS_JUST   VARCHAR2(61 CHAR),
      VAL_SH_FED NUMBER,
      VAL_SP_FED NUMBER,
      VAL_SH_GES NUMBER,
      VAL_SP_GES NUMBER,
      VAL_UCI    NUMBER,
      MARCA_UCI  VARCHAR2(10 CHAR),
      DIAGSEC1   VARCHAR2(10 CHAR),
      DIAGSEC2   VARCHAR2(10 CHAR),
      DIAGSEC3   VARCHAR2(10 CHAR),
      DIAGSEC4   VARCHAR2(10 CHAR),
      DIAGSEC5   VARCHAR2(10 CHAR),
      DIAGSEC6   VARCHAR2(10 CHAR),
      DIAGSEC7   VARCHAR2(10 CHAR),
      DIAGSEC8   VARCHAR2(10 CHAR),
      DIAGSEC9   VARCHAR2(10 CHAR),
      TPDISEC1   VARCHAR2(10 CHAR),
      TPDISEC2   VARCHAR2(10 CHAR),
      TPDISEC3   VARCHAR2(10 CHAR),
      TPDISEC4   VARCHAR2(10 CHAR),
      TPDISEC5   VARCHAR2(10 CHAR),
      TPDISEC6   VARCHAR2(10 CHAR),
      TPDISEC7   VARCHAR2(10 CHAR),
      TPDISEC8   VARCHAR2(10 CHAR),
      TPDISEC9   VARCHAR2(10 CHAR),
      FONTE_ORC  VARCHAR2(10 CHAR)   -- presente em 15/24 competencias
    ');
END;
/

-- A criacao NAO valida a URI: so falha na primeira consulta. Confira sempre.
SELECT COUNT(*) AS registros FROM BRZ_SIH_RD;
