-- BRZ_SINASC_DN — SINASC DN — declaracoes de nascido vivo
-- Gerado por scripts/gen_external_tables.py. Nao editar a mao.
-- Fonte: 3 arquivo(s), DNSP2020 a DNSP2022
-- Colunas: 61
--
-- Substitua <REGIAO>, <NAMESPACE> e <BUCKET> antes de rodar (veja sql/external_tables/uris.txt).

BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'BRZ_SINASC_DN',
    credential_name => 'OCI$RESOURCE_PRINCIPAL',
    file_uri_list   => 'https://objectstorage.<REGIAO>.oraclecloud.com/n/<NAMESPACE>/b/<BUCKET>/o/processed/sinasc/*.parquet',
    format          => JSON_OBJECT('type' VALUE 'parquet'),
    column_list     => '
      ORIGEM     VARCHAR2(10 CHAR),
      CODESTAB   VARCHAR2(10 CHAR),
      CODMUNNASC VARCHAR2(10 CHAR),
      LOCNASC    VARCHAR2(10 CHAR),
      IDADEMAE   VARCHAR2(10 CHAR),
      ESTCIVMAE  VARCHAR2(10 CHAR),
      ESCMAE     VARCHAR2(10 CHAR),
      CODOCUPMAE VARCHAR2(10 CHAR),
      QTDFILVIVO VARCHAR2(10 CHAR),
      QTDFILMORT VARCHAR2(10 CHAR),
      CODMUNRES  VARCHAR2(10 CHAR),
      GESTACAO   VARCHAR2(10 CHAR),
      GRAVIDEZ   VARCHAR2(10 CHAR),
      PARTO      VARCHAR2(10 CHAR),
      CONSULTAS  VARCHAR2(10 CHAR),
      DTNASC     VARCHAR2(10 CHAR),
      HORANASC   VARCHAR2(10 CHAR),
      SEXO       VARCHAR2(10 CHAR),
      APGAR1     VARCHAR2(10 CHAR),
      APGAR5     VARCHAR2(10 CHAR),
      RACACOR    VARCHAR2(10 CHAR),
      PESO       VARCHAR2(10 CHAR),
      IDANOMAL   VARCHAR2(10 CHAR),
      DTCADASTRO VARCHAR2(10 CHAR),
      CODANOMAL  VARCHAR2(25 CHAR),
      NUMEROLOTE VARCHAR2(10 CHAR),
      VERSAOSIST VARCHAR2(10 CHAR),
      DTRECEBIM  VARCHAR2(10 CHAR),
      DIFDATA    VARCHAR2(10 CHAR),
      DTRECORIGA VARCHAR2(10 CHAR),
      NATURALMAE VARCHAR2(10 CHAR),
      CODMUNNATU VARCHAR2(10 CHAR),
      CODUFNATU  VARCHAR2(10 CHAR),
      ESCMAE2010 VARCHAR2(10 CHAR),
      SERIESCMAE VARCHAR2(10 CHAR),
      DTNASCMAE  VARCHAR2(10 CHAR),
      RACACORMAE VARCHAR2(10 CHAR),
      QTDGESTANT VARCHAR2(10 CHAR),
      QTDPARTNOR VARCHAR2(10 CHAR),
      QTDPARTCES VARCHAR2(10 CHAR),
      IDADEPAI   VARCHAR2(10 CHAR),
      DTULTMENST VARCHAR2(10 CHAR),
      SEMAGESTAC VARCHAR2(10 CHAR),
      TPMETESTIM VARCHAR2(10 CHAR),
      CONSPRENAT VARCHAR2(10 CHAR),
      MESPRENAT  VARCHAR2(10 CHAR),
      TPAPRESENT VARCHAR2(10 CHAR),
      STTRABPART VARCHAR2(10 CHAR),
      STCESPARTO VARCHAR2(10 CHAR),
      TPNASCASSI VARCHAR2(10 CHAR),
      TPFUNCRESP VARCHAR2(10 CHAR),
      TPDOCRESP  VARCHAR2(10 CHAR),
      DTDECLARAC VARCHAR2(10 CHAR),
      ESCMAEAGR1 VARCHAR2(10 CHAR),
      STDNEPIDEM VARCHAR2(10 CHAR),
      STDNNOVA   VARCHAR2(10 CHAR),
      CODPAISRES VARCHAR2(10 CHAR),
      TPROBSON   VARCHAR2(10 CHAR),
      PARIDADE   VARCHAR2(10 CHAR),
      KOTELCHUCK VARCHAR2(10 CHAR),
      CONTADOR   VARCHAR2(10 CHAR)
    ');
END;
/

-- A criacao NAO valida a URI: so falha na primeira consulta. Confira sempre.
SELECT COUNT(*) AS registros FROM BRZ_SINASC_DN;
